---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  name: {{.Values.cluster_name}}-control-plane
spec:
  eksClusterName: {{.Values.cluster_name}}
  endpointAccess:
    public: true
    private: true
    publicCIDRs:
    {{- /* Security is IMPORTANT! Be sure to set this value! */}}
    {{- .Values.allowed_cidr_block | toYaml | nindent 4 }}
  roleAdditionalPolicies:
  - "arn:aws:iam::aws:policy/AmazonEKSVPCResourceController"
  iamAuthenticatorConfig: {}
  region: {{.Values.region}}
  sshKeyName: {{.Values.ssh_keyname}}
  version: {{.Values.k8s_version}}
