apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: philip-test-ns
  name: python-sample-deployment
  labels:
    app: python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-sample-app
          image: philiplee13/sample-python-app-k8s
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
