apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: hello-goodbye-pipeline-run
spec:
  pipelineRef:
    name: hello-goodbye-pipeline
  params:
    - name: helloUsername
      value: "philip hello username"
    - name: goodbyeUsername
      value: "philip goodbye username"
