apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set-pr-generator
  namespace: argocd
spec:
  # goTemplate: true
  # goTemplateOptions: ["missingkey=error"]
  generators:
    - pullRequest:
        github:
          # The GitHub organization or user.
          owner: philiplee13
          # The Github repository
          repo: k8s-learning
          # For GitHub Enterprise (optional)
          # api: https://git.example.com/
          # Reference to a Secret containing an access token. (optional)
          # tokenRef:
          #   secretName: github-token
          #   key: token
          # (optional) use a GitHub App to access the API instead of a PAT.
          # appSecretName: github-app-repo-creds
          # Labels is used to filter the PRs that you want to target. (optional)
          labels:
            - preview
        requeueAfterSeconds: 10
  template:
    metadata:
      name: "pr-generated-{{branch}}-{{number}}"
      namespace: argocd
    spec:
      source:
        repoURL: "https://github.com/philiplee13/k8s-learning.git"
        targetRevision: "{{head_sha}}"
        path: argo-cd/deployments/ # so this can be kustomize too
        directory:
          recurse: true
      project: "default"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{branch}}-{{number}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
