name: Integration tests
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
      - "**" # every single branch
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check directory
      - run: |
          ls -al
      # - name: Install script
      #   run: |
      #     chmod +x ../scripts/install.sh
      #     ../install.sh
      # - name: Apply and verify
      #   run: |
      #     chmod +x ../scripts/verify.sh
      #     ../verify.sh
