name: Integration tests
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
      - "**" # every single branch
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install k3s and kubectl
        run: |
          chmod +x ./scripts/install.sh
          ./scripts/install.sh

          chmod +x ./scripts/verify.sh
          ./scripts/verify.sh
