name: Integration tests
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
      - "**" # every single branch
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: check
      - uses: actions/checkout@v3
      - run: |
          ls -al
