name: Integration tests
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
      - "**" # every single branch
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install script
        run: |
          chmod +x ../scripts/install.sh
          ../install.sh
      - name: Apply and verify
        run: |
          chmod +x ../scripts/verify.sh
          ../verify.sh
